platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'RSMoneyMaker', :exclusive => true do
  pod "RSMoneyMaker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RSMoneyMaker", :path => "../"
end
